"""Paquete `tools`: implementaciones puras de las tools MCP de datos
(get_user_context, get_accounts...) más planificar_accion. Sin decoradores
de FastMCP — eso vive en server/mcp_server.py."""

from .tools import (  # noqa: F401
    confirm_transfer,
    get_account_detail,
    get_account_summary,
    get_accounts,
    get_all_transactions,
    get_budgets_monthly,
    get_credit_card_statements,
    get_credit_cards,
    get_daily_balance,
    get_expense_categories,
    get_reconciliation_status,
    get_savings_goals,
    get_statement_detail,
    get_statements,
    get_transactions,
    get_transfer_detail,
    get_transfers,
    get_user_context,
    planificar_accion,
    prepare_transfer,
    search_memory_context,
)

__all__ = [
    "confirm_transfer",
    "get_account_detail",
    "get_account_summary",
    "get_accounts",
    "get_all_transactions",
    "get_budgets_monthly",
    "get_credit_card_statements",
    "get_credit_cards",
    "get_daily_balance",
    "get_expense_categories",
    "get_reconciliation_status",
    "get_savings_goals",
    "get_statement_detail",
    "get_statements",
    "get_transactions",
    "get_transfer_detail",
    "get_transfers",
    "get_user_context",
    "planificar_accion",
    "prepare_transfer",
    "search_memory_context",
]
