"""Paquete `schemas`: modelos Pydantic compartidos, alineados con los DTOs
reales de backend/src/BancaAdaptativa.Api/Dtos/**.

Se re-exporta todo desde `schemas.schemas` para poder seguir escribiendo
`from app.schemas import Account, Transfer, ActionPlan` como antes.
"""

from .schemas import (  # noqa: F401
    ACTION_ID_ALIASES,
    ACTION_PLAN_SCHEMA,
    CANONICAL_ACTION_IDS,
    CANONICAL_INTENTS,
    DEFAULT_UI_HINT_BY_TOOL,
    INTENT_ALIASES,
    STEP_ARGUMENT_PLACEHOLDER_DEFAULTS,
    STEP_ARGUMENT_REAL_DEFAULTS,
    SUGGESTED_ACTION_ARGUMENT_FIELDS,
    TOOL_ALIASES,
    TOOL_NAMES,
    AccessibilityPreference,
    AccessibilityProfile,
    Account,
    AccountSummary,
    ActionPlan,
    AuditLog,
    BadgeTone,
    Budget,
    BudgetMonthlySummary,
    ComponentVariant,
    CreditCard,
    CreditCardStatement,
    DailyBalance,
    ExpenseCategory,
    IconType,
    MemoryEvent,
    PlannedStep,
    Priority,
    ReconciliationMatch,
    SavingsGoal,
    Statement,
    StatementDetail,
    StatementExpenseBreakdown,
    StepArguments,
    ToolName,
    Transaction,
    Transfer,
    TransferConfirmation,
    TransferStatus,
    UIHint,
    UserContext,
)
