// <auto-generated />
using System;
using BancaAdaptativa.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancaAdaptativa.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912174255_StatementsBudgetsGoalsCards")]
    partial class StatementsBudgetsGoalsCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BancaAdaptativa.Api.Models.AccessibilityPreference", b =>
                {
                    b.Property<int>("IdPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<float>("FontScale")
                        .HasColumnType("REAL");

                    b.Property<bool>("HighContrast")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LargeTargets")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlainLanguage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReducedMotion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPreference");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("AccessibilityPreferences");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaskedNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdAccount");

                    b.HasIndex("IdUser");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedactedPayload")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUser");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Budget", b =>
                {
                    b.Property<int>("IdBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentSpent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdExpenseCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdBudget");

                    b.HasIndex("IdExpenseCategory");

                    b.HasIndex("IdUser", "IdExpenseCategory", "Month", "Year")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.CreditCard", b =>
                {
                    b.Property<int>("IdCreditCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvailableCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNumberMasked")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDueDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatementCutOffDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCreditCard");

                    b.HasIndex("IdUser");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.CreditCardStatement", b =>
                {
                    b.Property<int>("IdCreditCardStatement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvailableCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCreditCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdStatement")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InterestCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentDueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPayments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPurchases")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCreditCardStatement");

                    b.HasIndex("IdCreditCard");

                    b.HasIndex("IdStatement")
                        .IsUnique();

                    b.ToTable("CreditCardStatements");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.DailyBalance", b =>
                {
                    b.Property<int>("IdBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Expenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdAccount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdBalance");

                    b.HasIndex("IdAccount", "Date")
                        .IsUnique();

                    b.ToTable("DailyBalances");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.DetectedPreference", b =>
                {
                    b.Property<int>("IdDetected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasedOnEventsCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("IdDetected");

                    b.HasIndex("IdUser");

                    b.ToTable("DetectedPreferences");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCategory");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.MemoryEvent", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdDetectedPreference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSession")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RedactedSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetentionUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("SensitivityLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetElement")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEvent");

                    b.HasIndex("IdDetectedPreference");

                    b.HasIndex("IdSession");

                    b.HasIndex("IdUser");

                    b.ToTable("MemoryEvents");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.ReconciliationMatch", b =>
                {
                    b.Property<int>("IdMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTransaction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTransfer")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MatchScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMatch");

                    b.HasIndex("IdTransaction")
                        .IsUnique();

                    b.HasIndex("IdTransfer")
                        .IsUnique();

                    b.ToTable("ReconciliationMatches");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.SavingsGoal", b =>
                {
                    b.Property<int>("IdGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("IdGoal");

                    b.HasIndex("IdUser");

                    b.ToTable("SavingsGoals");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Session", b =>
                {
                    b.Property<int>("IdSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceContext")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("IdSession");

                    b.HasIndex("IdUser");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Statement", b =>
                {
                    b.Property<int>("IdStatement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CutOffDay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAccount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStatement");

                    b.HasIndex("IdAccount", "PeriodStart")
                        .IsUnique();

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.StatementExpense", b =>
                {
                    b.Property<int>("IdStatementExpense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstTransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdExpenseCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdStatement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStatementExpense");

                    b.HasIndex("IdExpenseCategory");

                    b.HasIndex("IdStatement", "IdExpenseCategory")
                        .IsUnique();

                    b.ToTable("StatementExpenses");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Transaction", b =>
                {
                    b.Property<int>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAccount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdExpenseCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdTransaction");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdExpenseCategory");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Transfer", b =>
                {
                    b.Property<int>("IdTransfer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationAlias")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationMasked")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdOriginAccount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdTransfer");

                    b.HasIndex("IdOriginAccount");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.TransferConfirmation", b =>
                {
                    b.Property<int>("IdConfirmation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTransfer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdConfirmation");

                    b.HasIndex("IdTransfer");

                    b.ToTable("TransferConfirmations");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.UserProfile", b =>
                {
                    b.Property<int>("IdProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisabilityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProfile");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.AccessibilityPreference", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithOne("AccessibilityPreference")
                        .HasForeignKey("BancaAdaptativa.Api.Models.AccessibilityPreference", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Account", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.AuditLog", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Budget", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Budgets")
                        .HasForeignKey("IdExpenseCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.CreditCard", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("CreditCards")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.CreditCardStatement", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.CreditCard", "CreditCard")
                        .WithMany("CreditCardStatements")
                        .HasForeignKey("IdCreditCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancaAdaptativa.Api.Models.Statement", "Statement")
                        .WithOne("CreditCardStatement")
                        .HasForeignKey("BancaAdaptativa.Api.Models.CreditCardStatement", "IdStatement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.DailyBalance", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.Account", "Account")
                        .WithMany("DailyBalances")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.DetectedPreference", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("DetectedPreferences")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.MemoryEvent", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.DetectedPreference", "DetectedPreference")
                        .WithMany("MemoryEvents")
                        .HasForeignKey("IdDetectedPreference")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BancaAdaptativa.Api.Models.Session", "Session")
                        .WithMany("MemoryEvents")
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("MemoryEvents")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetectedPreference");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.ReconciliationMatch", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.Transaction", "Transaction")
                        .WithOne("ReconciliationMatch")
                        .HasForeignKey("BancaAdaptativa.Api.Models.ReconciliationMatch", "IdTransaction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancaAdaptativa.Api.Models.Transfer", "Transfer")
                        .WithOne("ReconciliationMatch")
                        .HasForeignKey("BancaAdaptativa.Api.Models.ReconciliationMatch", "IdTransfer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.SavingsGoal", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("SavingsGoals")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Session", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Statement", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.Account", "Account")
                        .WithMany("Statements")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.StatementExpense", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("StatementExpenses")
                        .HasForeignKey("IdExpenseCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancaAdaptativa.Api.Models.Statement", "Statement")
                        .WithMany("StatementExpenses")
                        .HasForeignKey("IdStatement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Transaction", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancaAdaptativa.Api.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Transactions")
                        .HasForeignKey("IdExpenseCategory")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Transfer", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.Account", "OriginAccount")
                        .WithMany("Transfers")
                        .HasForeignKey("IdOriginAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithMany("Transfers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.TransferConfirmation", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.Transfer", "Transfer")
                        .WithMany("Confirmations")
                        .HasForeignKey("IdTransfer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.UserProfile", b =>
                {
                    b.HasOne("BancaAdaptativa.Api.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("BancaAdaptativa.Api.Models.UserProfile", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Account", b =>
                {
                    b.Navigation("DailyBalances");

                    b.Navigation("Statements");

                    b.Navigation("Transactions");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.CreditCard", b =>
                {
                    b.Navigation("CreditCardStatements");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.DetectedPreference", b =>
                {
                    b.Navigation("MemoryEvents");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("StatementExpenses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Session", b =>
                {
                    b.Navigation("MemoryEvents");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Statement", b =>
                {
                    b.Navigation("CreditCardStatement");

                    b.Navigation("StatementExpenses");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Transaction", b =>
                {
                    b.Navigation("ReconciliationMatch");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.Transfer", b =>
                {
                    b.Navigation("Confirmations");

                    b.Navigation("ReconciliationMatch");
                });

            modelBuilder.Entity("BancaAdaptativa.Api.Models.User", b =>
                {
                    b.Navigation("AccessibilityPreference");

                    b.Navigation("Accounts");

                    b.Navigation("AuditLogs");

                    b.Navigation("Budgets");

                    b.Navigation("CreditCards");

                    b.Navigation("DetectedPreferences");

                    b.Navigation("MemoryEvents");

                    b.Navigation("SavingsGoals");

                    b.Navigation("Sessions");

                    b.Navigation("Transfers");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
